apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: API
metadata:
  name: apitest-private-nlb
spec:
  body: '{
    "openapi": "3.0.1",
    "info": {
        "title": "ack-apigwv2-import-test-private-nlb",
        "version": "v1"
    },
    "paths": {
        "default": {
            "x-amazon-apigateway-any-method" : {
                "isDefaultRoute" : true,
                "x-amazon-apigateway-integration" : {
                    "payloadFormatVersion" : "1.0",
                    "connectionId" : "289b8t",
                    "type" : "http_proxy",
                    "httpMethod" : "GET",
                    "uri" : "arn:aws:elasticloadbalancing:sa-east-1:991345343226:listener/net/k8s-default-authorse-dcc7e5f7e2/577cf814e9dad217/accf24ccc5dfff0a",
                    "connectionType" : "VPC_LINK"
                }
            }
        },
        "/meta": {
            "get": {
                "x-amazon-apigateway-integration": {
                    "uri" : "arn:aws:elasticloadbalancing:sa-east-1:991345343226:listener/net/k8s-default-echoserv-6c5f6f2eca/6a7b4427bb20762f/91ce1b29690f6071",
                    "httpMethod": "GET",
                    "connectionId": "289b8t",
                    "type": "HTTP_PROXY",
                    "connectionType": "VPC_LINK",
                    "payloadFormatVersion": "1.0"
                }
            }
        }
    },
    "components": {}
}'