apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: VPCLink
metadata:
  name: nlb-internal
spec:
  name: nlb-internal
  securityGroupIDs: 
    - sg-0fdad8ff734204d58
  subnetIDs: 
    - subnet-0cecef759724ea219
    - subnet-0828a1930bdf45b60
    - subnet-0ac010bb1e722af0a