apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: VPCLink
metadata:
  name: nlb-internal
spec:
  name: nlb-internal
  securityGroupIDs: 
    - sg-0a736574b19725498
  subnetIDs: 
    - subnet-019b954a5832c5cdb
    - subnet-09d04df505bcafe3b
    - subnet-0005fed6abc01be8b